# Generated by Django 3.0.6 on 2022-03-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_auto_20220308_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='offspring',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='parent',
        ),
        migrations.AddField(
            model_name='individual',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_of_father', to='create.individual'),
        ),
        migrations.AddField(
            model_name='individual',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of_mother', to='create.individual'),
        ),
    ]
