# Generated by Django 3.0.6 on 2022-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0009_auto_20220310_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
