# Generated by Django 3.0.6 on 2022-03-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0010_auto_20220310_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='gender',
        ),
    ]
