# Generated by Django 3.0.6 on 2022-03-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0012_individual_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='id',
        ),
        migrations.AlterField(
            model_name='individual',
            name='first_Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
