# Generated by Django 3.0.6 on 2022-03-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0013_auto_20220312_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personA', models.CharField(max_length=100)),
                ('personB', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('S', 'Spouse'), ('F', 'Father'), ('M', 'Mother')], default=None, max_length=20)),
            ],
        ),
    ]
