# Generated by Django 3.0.6 on 2022-03-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0014_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Spouse', to='create.individual'),
        ),
    ]
