# Generated by Django 3.0.6 on 2022-03-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0015_individual_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='first_Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
