# Generated by Django 3.0.6 on 2022-03-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0016_auto_20220313_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='first_Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='last_Name',
        ),
    ]
