# Generated by Django 3.0.6 on 2022-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0022_auto_20220320_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='id',
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
