# Generated by Django 3.0.6 on 2022-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0025_auto_20220321_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
