# Generated by Django 3.0.6 on 2022-03-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0026_auto_20220321_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
